domain: fbbdev.it

name: fbbdev.it
author: Fabio Massaioli (fbbdev)
description: fbbdev.it is the place for everything crossing my mind

collections:
    writings:
        output: true
        permalink: /writings/:path
    projects:
        output: true
        permalink: /projects/:path
    tools:
        output: true
        permalink: /tools/:path

defaults:
    - scope:
          path: ""
          type: writings
      values:
          layout: article
    - scope:
          path: ""
          type: projects
      values:
          layout: project
    - scope:
          path: ""
          type: tools
      values:
          layout: page

sass:
    style: :compressed

# gem:
#    - octopress-debugger
