domain: fbbdev.it

name: fbbdev.it
author: Fabio Massaioli (fbbdev)
description: fbbdev.it is my personal website where I publish projects and make experiments in web development.

sass:
    style: :compressed
